apiVersion: v1
kind: Pod
metadata:
  name: ds
spec:
  containers:
    - args:
      - ./bin/run-cluster.sh
      - 1:2:1
      - --train_files=ldc93s1/ldc93s1.csv
      - --dev_files=ldc93s1/ldc93s1.csv
      - --test_files=ldc93s1/ldc93s1.csv
      - --log_level=0
      - --train_batch_size=128
      - --benchmark_steps=20
      - --notest
      name: ds-container
      image: piotrowskidariusz/deepspeech:patched
      env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0,1"
      resources:
        limits:
          nvidia.com/gpu: 2
  restartPolicy: Never
